const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('overlay', {
  minimize: () => ipcRenderer.send('window-minimize'),
  logoCollapseReady: (details) => ipcRenderer.send('window-logo-collapse-ready', details),
  restoreFromLogo: () => ipcRenderer.send('window-logo-restore'),
  logoRestoreReady: () => ipcRenderer.send('window-logo-restore-ready'),
  logoDragStart: (x, y) => ipcRenderer.send('window-logo-drag-start', x, y),
  logoDragMove: (x, y) => ipcRenderer.send('window-logo-drag-move', x, y),
  logoDragEnd: () => ipcRenderer.send('window-logo-drag-end'),
  toggleLogoAnchor: () => ipcRenderer.send('window-logo-toggle-anchor'),
  onLogoCollapseRequested: (callback) => ipcRenderer.on('logo-collapse-request', (_, target) => callback(target)),
  onLogoRestoreMain: (callback) => ipcRenderer.on('logo-restore-main', () => callback()),
  onCollapsedLogoShow: (callback) => ipcRenderer.on('collapsed-logo-show', () => callback()),
  onCollapsedLogoHide: (callback) => ipcRenderer.on('collapsed-logo-hide', () => callback()),
  onCollapsedLogoMotion: (callback) => ipcRenderer.on('collapsed-logo-motion', (_, motion) => callback(motion)),
  onCollapsedLogoAnchorChanged: (callback) => ipcRenderer.on('collapsed-logo-anchor-changed', (_, anchored) => callback(anchored)),
  close: () => ipcRenderer.send('window-close'),
  setOpacity: (val) => ipcRenderer.send('window-set-opacity', val),
  setOpacityLock: (locked) => ipcRenderer.send('window-set-opacity-lock', locked),
  toggleAlwaysOnTop: () => ipcRenderer.send('window-toggle-top'),
  setAlwaysOnTop: (val) => ipcRenderer.send('window-set-always-on-top', val),
  toggleLockPosition: () => ipcRenderer.send('window-toggle-lock'),
  onPositionLocked: (callback) => ipcRenderer.on('position-locked', (_, locked) => callback(locked)),
  toggleWidgetMode: () => ipcRenderer.send('window-toggle-widget'),
  toggleFullscreen: () => ipcRenderer.send('window-toggle-fullscreen'),
  onFullscreenChanged: (callback) => ipcRenderer.on('fullscreen-changed', (_, isFs) => callback(isFs)),
  setWindowSizes: (widget, full) => ipcRenderer.send('window-set-sizes', widget, full),
  onWindowResizeDimensions: (callback) => ipcRenderer.on('window-resize-dimensions', (_, dimensions) => callback(dimensions)),
  confirmQuit: () => ipcRenderer.send('window-confirm-quit'),
  requestFocus: () => ipcRenderer.send('window-request-focus'),
  releaseFocus: () => ipcRenderer.send('window-release-focus'),
  onWidgetModeChanged: (callback) => ipcRenderer.on('widget-mode-changed', (_, isWidget) => callback(isWidget)),
  onWidgetTransitionStart: (callback) => ipcRenderer.on('widget-transition-start', () => callback()),
  onMinimizedState: (callback) => ipcRenderer.on('minimized-state', (_, minimized) => callback(minimized)),
  onCloseRequested: (callback) => ipcRenderer.on('close-requested', () => callback()),
  minimizeToTaskbar: () => ipcRenderer.send('window-minimize-taskbar'),
  minimizeNormal: () => ipcRenderer.send('window-minimize-normal'),
  expandCollapsedForQuit: () => ipcRenderer.send('window-expand-for-quit'),
  collapseAfterQuitCancel: () => ipcRenderer.send('window-collapse-after-quit'),
  snapLeft: () => ipcRenderer.send('window-snap-left'),
  snapRight: () => ipcRenderer.send('window-snap-right'),
  onWindowSnapped: (callback) => ipcRenderer.on('window-snapped', (_, side) => callback(side)),
  dragStart: (x, y) => ipcRenderer.send('window-drag-start', x, y),
  dragMove: (x, y) => ipcRenderer.send('window-drag-move', x, y),
  dragEnd: () => ipcRenderer.send('window-drag-end'),
  collapsedResizeStart: (edge) => ipcRenderer.send('window-collapsed-resize-start', edge),
  collapsedResizeMove: (x) => ipcRenderer.send('window-collapsed-resize-move', x),
  collapsedResizeEnd: () => ipcRenderer.send('window-collapsed-resize-end'),
  onNativeKey: (callback) => ipcRenderer.on('native-key', (_, data) => callback(data)),
  onNativeHotkey: (callback) => ipcRenderer.on('native-hotkey', (_, data) => callback(data)),
  onNativeInputStop: (callback) => ipcRenderer.on('native-input-stop', () => callback()),
  getVersion: () => ipcRenderer.invoke('get-app-version'),
  getGraphicsStatus: () => ipcRenderer.invoke('get-graphics-status'),
  recordCrashProbe: (eventName, details) => ipcRenderer.invoke('record-crash-probe', eventName, details),
  getCrashReportPath: () => ipcRenderer.invoke('get-crash-report-path'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  exportBlueprintXml: (name, xml) => ipcRenderer.invoke('export-blueprint-xml', name, xml),
  importBlueprintXml: () => ipcRenderer.invoke('import-blueprint-xml'),
  // `clipboard` from require('electron') is undefined in a sandboxed preload, so
  // route through the main process. Read stays synchronous (sendSync) to preserve the
  // existing call sites that use the return value directly.
  clipboardWrite: (text) => ipcRenderer.send('clipboard-write', text),
  clipboardRead: () => ipcRenderer.sendSync('clipboard-read-sync'),
  openSaveFile: () => ipcRenderer.invoke('open-save-file'),
  readSaveFile: (filePath) => ipcRenderer.invoke('read-save-file', filePath),
  readSaveFileChunk: (filePath, offset, bytes) => ipcRenderer.invoke('read-save-file-chunk', filePath, offset, bytes),
  exportEditedSave: (defaultName, text) => ipcRenderer.invoke('export-edited-save', defaultName, text),
  scanXenotypeDefs: (dirPath) => ipcRenderer.invoke('scan-xenotype-defs', dirPath),
  scanTraitGeneDefs: (dirPath, options) => ipcRenderer.invoke('scan-trait-gene-defs', dirPath, options),
  findRimworldPath: () => ipcRenderer.invoke('find-rimworld-path'),
  onTraitGeneScanProgress: (callback) => {
    ipcRenderer.removeAllListeners('trait-gene-scan-progress');
    ipcRenderer.on('trait-gene-scan-progress', (_, data) => callback(data));
  },
  scanDefLabels: (installPath) => ipcRenderer.invoke('scan-def-labels', installPath),
  onDefLabelProgress: (callback) => ipcRenderer.on('def-label-progress', (_, data) => callback(data)),
  pickDirectory: (defaultPath) => ipcRenderer.invoke('pick-directory', defaultPath),
  loadAppState: (source) => ipcRenderer.sendSync('load-app-state-sync', source),
  saveAppState: (json) => ipcRenderer.invoke('save-app-state', json),
  saveToFile: (filePath, json) => ipcRenderer.invoke('save-to-file', filePath, json),
  loadFromFile: (filePath) => ipcRenderer.invoke('load-from-file', filePath),
  pickSaveLocation: (defaultPath) => ipcRenderer.invoke('pick-save-location', defaultPath),
  scanModEquipment: (installPath, options) => ipcRenderer.invoke('scan-mod-equipment', installPath, options),
  onModScanProgress: (callback) => {
    ipcRenderer.removeAllListeners('mod-scan-progress');
    ipcRenderer.on('mod-scan-progress', (_, data) => callback(data));
  },
  // Cold-open: apply the startup mode instantly while hidden, then signal ready to reveal.
  applyStartupMode: (mode) => ipcRenderer.send('apply-startup-mode', mode),
  rendererReady: () => ipcRenderer.send('renderer-ready'),
  setNativeTheme: (theme) => ipcRenderer.send('set-native-theme', theme)
});
